name: Validate Common Library
on:
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Validate Common automation scipt name
        run: |
          if grep -qE "<Name>([a-zA-Z0-9_]+MediaOpsCommon[a-zA-Z0-9_]+|MediaOpsCommon[a-zA-Z0-9_]+|[a-zA-Z0-9_]+MediaOpsCommon)</Name>" ./*; then
            echo "Variations of 'MediaOpsCommon' automation script name found. Is this intentional?"
            exit 1
          else
            echo "'MediaOpsCommon' automation script found. Proceeding."
          fi
      - name: Validate Common automation script library name
        run: |
          if grep -qE "<Param type=\"libraryName\">([a-zA-Z0-9_]+MediaOpsCommon[a-zA-Z0-9_]+|MediaOpsCommon[a-zA-Z0-9_]+|[a-zA-Z0-9_]+MediaOpsCommon)</Param>" ./*; then
            echo "Variations of 'MediaOpsCommon' automation script library name found. Is this intentional?"
            exit 1
          else
            echo "'MediaOpsCommon' automation script library found. Proceeding."
          fi