name: Validate Common Library
on:
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Common automation scipt name
        run: |
          if grep -qE "<Name>MediaOpsCommon</Name>" MediaOpsCommon.xml; then
            echo "'MediaOpsCommon' automation script found. Proceeding."
          else
            echo "Usual 'MediaOpsCommon' automation script name seems to be changed. Is this intentional?"
            exit 1
          fi
      - name: Validate Common automation script library name
        run: |
          if grep -qE "<Param type=\"libraryName\">MediaOpsCommon</Param>" MediaOpsCommon.xml; then
            echo "'MediaOpsCommon' library found. Proceeding."
          else
            echo "Usual 'MediaOpsCommon' library name seems to be changed. Is this intentional?"
            exit 1
          fi